#include "globals.h"



struct TkabTRAK thisCabinet;
//DynamicArray< TDrawer > thisDrawer;

//TTools thisTool;
//DynamicArray< TTransaction > thisTransactions;
//TCurrentTools thisCurrentTools[ 150/*# range 1..150*/ ];
//TBarCode thisBarCode;
//TJvLED DrawerLEDs[ 10/*# range 1..10*/ ];
QString SavePressedKey;
bool SummaryFormActive = false;
bool ToolReturnActive = false;
bool MessageBoxActive = false;
int tools_available = 0;
int tools_issued_current_user = 0;
int tools_issued_other_user = 0;
bool close_timer_fired = false;
QString UserID;
QString qryOutToolsSQL;
QString qryOutCribToolSQL;
QString ToolsOutSort;
bool UserConfrimedTransactions = false;
QString SQLFileName;
int ActiveDrawerNum = 0;
bool ActiveDrawerState = false;
bool ActiveOpenState = false;
bool ActiveToolChanged = false;
bool DiagramIsLoaded = false;
int BeforeCalibrationDays = 0;
bool AllowDrawerClose = false;
int Calibration = 0;
int CalibrationNotification = 0;
int CloseDrawerToLogOff = 0;
int OpenDrawerToAlarm = 0;
int AdminToLogOff = 0;
int CloseDrawerCounter = 0;
int OpenDrawerCounter = 0;
int AdminCounter = 0;
bool Online = false;
bool TailNumberActive = false;
bool BarcodeTestActive = false;
bool isBarcodeConnected = false;
bool CloseGuiActive = false;
bool WarningActive = false;
int TailCounter = 0;
int TailToLogOff = 0;
bool AdminTransactionActive = false;
int kabtrakTransferID = 0;
bool Transferring = false;
int CurrentTransactionID = 0;
int transfer_drawernum = 0;
int transfer_toolnum = 0;
bool PostToTransaction = false;
bool DrawersUnlock = false;
QString workorder_no;
QString batch_no;
int current_drawernum = 0;
bool ReloadDiagram = false;
int TrailID = 0;
bool isCardReaderConnected = false;
bool UpdateAvailable = false;
bool NoLayout = false;
int totaltools_na = 0;
bool DrawerOpenDelayisOn = false;
bool maintenanceactive = false;
QString ldr_bit_toolchange;
QString ldr_bit_open;
int TestActiveDrawer = 0;
bool AdminSettingsActive = false;
bool PostIt = false;
bool IssuedToOther = false;
bool ScannedOut = false;
bool DisconnectionScreenActive = false;
bool vKBVisible = false;
bool ReadToolOnly = false;
bool SelectJobActive = false;
//TRzButton SpeedDial[ 10/*# range 1..10*/ ];
bool EmailSent = false;
QString logSQL;
bool DrawToolMaintActive = false;
bool CabinetSetupActive = false;
bool TerminalActive = false;
bool ToolDrawActive = false;
bool mainActive = false;
bool ToolPropertyActive = false;
//int CurrentAttempt = 0;
bool DisplayToolNumberActive = false;
